port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# telling Jekyll the name of our site and what version of Markdown we'd like to use
name: Junyi Yang Portfolio Website
# permalink: /blog/:year/:month/:day/:title