social_label: Connect
social:
- {icon: 'github',    link: 'https://github.com/lenpaul'}
- {icon: 'linkedin',  link: 'https://linkedin.com/in/lenpaul'}
- {icon: 'envelope',  link: 'mailto:mailto:l.nguyen.paul@gmail.com'}